networks:
  internal:
    driver: bridge

services:

  postgres:
    image: postgres:15
    container_name: postgres
    env_file: .env
    networks:
      - internal
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: redis
    networks:
      - internal
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  backend:
    ports:
      - "8000:8000"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    env_file: .env
    networks:
      - internal
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - logs_volume:/app/logs
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_worker
    env_file: .env
    networks:
      - internal
    command: celery -A app.workers worker -l info
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_beat
    env_file: .env
    networks:
      - internal
    command: celery -A app.workers beat -l info
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

volumes:
  postgres_data:
  redis_data:
  logs_volume:
